### ISSUE TITLE
Run the network

### ISSUE THREAD

**Issue by karon503** [luiserrador/IndVertSeg_VerSe#5]
Hello, I will appreciate it very much if you can give me some guidance on how to use the trained network to generate the slice level heatmap and segmentated image. Thanks.

**Comment by luiserrador** [comment]
Hello @karon503 

Here you can find the pseudocode for vertebrae segmentation:
![inference_vertebrae_segmentation](https://github.com/luiserrador/IndVertSeg_VerSe/assets/25669570/69d4427d-7d1a-4c45-8002-ce271a34975e)

I'll add it to the readme section of the repo. Thanks for your comment. Let me know if I asked your question so I can close the issue.

**Comment by karon503** [comment]
Thank you very much and I will try to turn it to code!
